### ISSUE TITLE
null safety support

### ISSUE THREAD

**Issue by salahkamal** [shah-xad/webview_flutter_plus#16]
any new updates ??

**Comment by NuteIla** [comment]
Waiting on this as well.

**Comment by shah-xad** [comment]
It's done please consider `webview_flutter_plus: ^0.2.0`

**Comment by shah-xad** [comment]
Hi, I'm sorry but I have to restart this package as I found some issue with webview_flutter. Now, `webview_flutter_plus` is much improved than its previous versions. Please give it a try now. And check if your issue persists is webview_flutter then it'll also be here because it's just an extension of that.
