### ISSUE TITLE
How to create link url in WebView

### ISSUE THREAD

**Issue by xarmatura** [shah-xad/webview_flutter_plus#23]
Hello @shah-xad, could you help me, I'm using

```
onWebViewCreated: (controller) {
                _controller = controller;
                _controller!
                    .loadUrl(Uri.dataFromString(_sharedState.message!.body!, mimeType: 'text/html', encoding: Encoding.getByName('utf-8')).toString());
              },
```

```
navigationDelegate: (request) async {
          final String? url = request.url;
          if (url != null && (url.startsWith('http') || url.startsWith('www'))) {
            UrlLaunchHelper.tryLaunch(url);
            return NavigationDecision.prevent;
          }
          return NavigationDecision.navigate;
        },
```

**and response** data:text/html;charset=utf-8,%3Cp%3Ehttps://www.youtube.com/watch?v=BrGpNPvBu4c%3C/p%3E

**Comment by shah-xad** [comment]
Hi, I'm sorry but I have to restart this package as I found some issue with webview_flutter. Now, `webview_flutter_plus` is much improved than its previous versions. Please give it a try now. And check if your issue persists is webview_flutter then it'll also be here because it's just an extension of that.
