### ISSUE TITLE
How to use local image assets?

### ISSUE THREAD

**Issue by Nialixus** [shah-xad/webview_flutter_plus#24]
Hi there, I created a wysiwyg editor using this webview, and it requires me to be able to insert **local image assets**. do you have a way to do that? 

Btw i'm using localhtml by string.

**Comment by Nialixus** [comment]
whoop, i guess i just need to convert it to base64.

**Comment by shah-xad** [comment]
Hi, I'm sorry but I have to restart this package as I found some issue with webview_flutter. Now, `webview_flutter_plus` is much improved than its previous versions. Please give it a try now. And check if your issue persists is webview_flutter then it'll also be here because it's just an extension of that.
