### ISSUE TITLE
Add support for flutter desktop

### ISSUE THREAD

**Issue by SachinBhankhar** [shah-xad/webview_flutter_plus#4]

**Comment by shah-xad** [comment]
This package has been `deprecated` in the favor of [webview_flutter](https://pub.dartlang.org/packages/webview_flutter). This package was developed because [webview_flutter](https://pub.dartlang.org/packages/webview_flutter) lacked some important features at that time, like loading local HTML, CSS, and Javascript content from Assets or Strings. But, now [webview_flutter](https://pub.dartlang.org/packages/webview_flutter) provides all this stuff since `webview_flutter: ^2.4.0`. It's highly recommended to use [webview_flutter](https://pub.dartlang.org/packages/webview_flutter) for better performance and better support.

**Comment by shah-xad** [comment]
Hi, I'm sorry but I have to restart this package as I found some issue with webview_flutter. Now, `webview_flutter_plus` is much improved than its previous versions. Please give it a try now. And check if your issue persists is webview_flutter then it'll also be here because it's just an extension of that.
